"""Regenerate static clean-URL entry points after editing the root HTML pages."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
ROUTES = {
    "home": "index.html",
    "projects": "index.html",
    "community": "index.html",
    "case-study": "index.html",
    "graphics": "index.html",
    "about": "about.html",
    "art": "art.html",
    "resume": "resume.html",
}

for route, source in ROUTES.items():
    directory = ROOT / route
    directory.mkdir(exist_ok=True)
    (directory / "index.html").write_text(
        "<!-- Generated by build_routes.py; edit the root HTML source instead. -->\n"
        + (ROOT / source).read_text()
    )
